export const CONFIG = {
    CAPACIDAD_BUS: 40,
    COSTO_TICKET: 50,
    TIEMPO_VIAJE: 3000,
    TIEMPO_ABORDAJE: 1000,
    INTERVALO_GENERACION: 2000,
    PROBABILIDAD_DINERO: 0.8,
    PROBABILIDAD_DESCENSO: 0.6
};
